services:
  airflow:
    image: apache/airflow:3.0.6
    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    command: api-server

volumes:
  airflow_data: